---
# Username for Apache service, used to set permissions on the
# Source Interface config to enable logging in the staging environment.
apache_user: www-data

# Additional apt packages required for running the application tests.
test_apt_dependencies:
  - xvfb

# Additional Python dependencies required for running the application tests.
test_pip_requirements: "{{ securedrop_code }}/requirements/test-requirements.txt"
