---
- include: staging_wsgi_files.yml
  when: "'staging' in group_names"
  tags:
    - apache

- include: dev_setup_xvfb_for_functional_tests.yml

- include: setup_firefox_for_selenium.yml

- include: disable_mprotect_ff_plugin_container.yml

- include: modern_gettext.yml
